---
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/config:/etc/grafana
    ports:
      - 127.0.0.1:3000:3000

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - --path.rootfs=/host
      - --collector.processes
      - --collector.tcpstat
      - --collector.systemd
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro'
    security_opt:
      - apparmor:unconfined

  smartctl_exporter:
    image: prometheuscommunity/smartctl-exporter:latest
    restart: unless-stopped
    privileged: true
    user: root
